package com.kelab.usercenter.constant.enums;

public enum CacheBizName {
    LOG, USER_DAY_STATISTIC_REFRESH_END,
    VERIFY_CODE, USER_INFO, ONLINE_USER, SITE_SETTING,
    SCROLL_PICTURE_PAGE, NEWS_PAGE, NEWS_ROLL_PAGE, ABOUT_PAGE, COMPETITION_PAGE,/*分页查询缓存*/
    SCROLL_PICTURE, NEWS, NEWS_ROLL, ABOUT, COMPETITION, COMPETITION_STUDENT, USER_DAY_STATISTIC
}
